### PR TITLE
add: cluster contact list

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Review by drfaustusfade — COMMENTED** [review]
if(user_level>=4){
          ...
 }

that is better not to do like that
if the level is updated, this will silently create an issue

maybe to create MULTICOUNTRY: true/false permission attribute on roles to show/not show specific multicountry features if needed
level should be just for comparing user level

**Comment by drfaustusfade** [comment]
ROLE: 'COUNTRY_ADMIN', is not MULTICOUNTRY

**Comment by fakhrihawari** [comment]
> if(user_level>=4){
> ...
> }
> 
> that is better not to do like that
> if the level is updated, this will silently create an issue
> 
> maybe to create MULTICOUNTRY: true/false permission attribute on roles to show/not show specific multicountry features if needed
> level should be just for comparing user level

ok

**Comment by drfaustusfade** [comment]
please declare variables as we are going to switch to use strict mode

**Pull request merged**
