### PR TITLE
update: start date dashboard

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Review by drfaustusfade — COMMENTED** [review]
why using this...
can just variable be used?

**Comment by fakhrihawari** [comment]
okay

**Comment by drfaustusfade** [comment]
please also check/update same with this.page in a separate commit

**Comment by fakhrihawari** [comment]
updated

**Comment by fakhrihawari** [comment]
> please also check/update same with this.page in a separate commit
> https://github.com/drfaustusfade/ngm-reportHub/blob/e93995d97c690aeecc1433d9a2f06a10e552b758/app/scripts/modules/cluster/app.js#L34

okay

**Review by drfaustusfade — COMMENTED** [review]
but also having an object to run functions rather than static
```
var page = { 
anyFn : function(){},
}
or..
var _this 
...
_this.page 
or
```

**Comment by fakhrihawari** [comment]
> but also having an object to run functions rather than static
> 
> ```
> var page = { 
> anyFn : function(){},
> }
> or..
> var _this 
> ...
> _this.page 
> or
> ```

this.page = {
			start_date: function() {
				var date;
				if ( moment.utc().date() <= 20 ) {
					date = moment.utc().startOf( 'M' ).subtract( 1, 'M').format( 'YYYY-MM-DD' )
				} else {
					date = moment.utc().startOf( 'M' ).format( 'YYYY-MM-DD' );
				}
				return date;
			},
			end_date: function() {
				var date;
				if ( moment.utc().date() <= 20 ) {
					date = moment.utc().endOf( 'M' ).subtract( 1, 'M').format( 'YYYY-MM-DD' )
				} else {
					date = moment.utc().endOf( 'M' ).format( 'YYYY-MM-DD' );
				}
				return date;
			},
		}
		const page_start_date = this.page.start_date();
		const page_end_date = this.page.end_date();
like this?

**Comment by drfaustusfade** [comment]
just like it was but not attaching page or dashboards to _this_ 
running fn on routes is needed to have dynamic dates ( even though year rarely change :) )

**Comment by fakhrihawari** [comment]
> just like it was but not attaching page or dashboards to _this_
> running fn on routes is needed to have dynamic dates ( even though year rarely change :) )

updated

**Comment by drfaustusfade** [comment]
alright, please set also 5w to default moment().subtract(2, 'M').year().toString()

**Comment by fakhrihawari** [comment]
> alright, please set also 5w to default moment().subtract(2, 'M').year().toString()

updated

**Pull request merged**
