### PR TITLE
update: add infinite scroll  on project plan and monthly report

### PR DESCRIPTION
**Pull request by fakhrihawari**

### CODE REVIEW

**Comment by drfaustusfade** [comment]
chrome_sBE8ayosnj
only one location shown and no scroll, @fakhrihawari is it the same for you?

**Comment by fakhrihawari** [comment]
> chrome_sBE8ayosnj
> only one location shown and no scroll, @fakhrihawari is it the same for you?

Yes, i already fix that but not push it yet

**Comment by fakhrihawari** [comment]
I already push the bugfix

**Comment by drfaustusfade** [comment]
> I already push the bugfix

perfect, please also on add more items functions add check if all items added so that to stop adding to counter and slicing items array

**Comment by fakhrihawari** [comment]
updated

**Comment by drfaustusfade** [comment]
with SetTimeout changes are not picked up sometimes by angular, $timeout should be used
also, can timeout be removed at all, so that no to run more digest cycles, is ngInfiniteScroll not handling that?

**Comment by fakhrihawari** [comment]
updated

**Comment by drfaustusfade** [comment]
looks alright, please test everything out once more so that works well with other functionality

**Comment by fakhrihawari** [comment]
Okay, i already do some testing on my local and its work well

**Comment by drfaustusfade** [comment]
please check that more than 7 location and 8 target beneficiaries can be added, because on mine add buttons disappear
also there seems to be bug not related to this pull on CB locations

**Comment by fakhrihawari** [comment]
> please check that more than 7 location and 8 target beneficiaries can be added, because on mine add buttons disappear
> also, there seems to be a bug not related to this pull on CB locations -- on location name from list selection is not responsive when selecting any option, that needs to be tested out

do you try scroll it ? and where this happen on montly or project plan?

**Comment by fakhrihawari** [comment]
> please check that more than 7 location and 8 target beneficiaries can be added, because on mine add buttons disappear
> also, there seems to be a bug not related to this pull on CB locations -- on location name from list selection is not responsive when selecting any option, that needs to be tested out

bugfix for add button , 
okay i will check it and test it and if need to push i will make PR using another branch

**Comment by drfaustusfade** [comment]
when tested, please make a pull
could you also put that part of handling adding count to list into separate function, next to other count related variables/functions

**Comment by fakhrihawari** [comment]
> when tested, please make a pull
> could you also put that part of handling adding count to list into separate function, next to other count related variables/functions

You mean  this one ? 
https://github.com/drfaustusfade/ngm-reportHub/pull/118/files#diff-af599ef128a376bf241f399f295cb87cb9894d7de5f01e7a3a246882a28d0d63R670

**Comment by drfaustusfade** [comment]
yep, for general functionality, that also could be as separate class later for handling infinite scroll lists

**Comment by fakhrihawari** [comment]
updated

**Comment by drfaustusfade** [comment]
alright, looks good, maybe if like that there is no need to pass the entire array, but just length,

**Comment by drfaustusfade** [comment]
there is some bug on custom grouping
when adding location, existing activities are messed up, and on navigation out/in added locations without same still there

**Comment by drfaustusfade** [comment]
On custom grouping 
1 existing activity on some location
chrome_qR0xN2w3id
2 adding new location
chrome_WrDnsi2gPe
3 activity appears on new location
chrome_J4kgOiv7JT
4 on reload activity on correct location but location seems to be saved

**Comment by fakhrihawari** [comment]
this is demo when add new location on monthly 
https://user-images.githubusercontent.com/12655589/112425658-03d05700-8d69-11eb-9ded-ef7e08627404.mp4

its work,
can you tell how to produce the bug?

**Comment by drfaustusfade** [comment]
> this is demo when add new location on monthly
> https://user-images.githubusercontent.com/12655589/112425658-03d05700-8d69-11eb-9ded-ef7e08627404.mp4
> 
> its work,
> can you tell how to produce the bug?

it's on custom grouping, is it custom group on video?

**Comment by fakhrihawari** [comment]
> > this is demo when add new location on monthly
> > https://user-images.githubusercontent.com/12655589/112425658-03d05700-8d69-11eb-9ded-ef7e08627404.mp4
> > its work,
> > can you tell how to produce the bug?
> 
> it's on custom grouping, is it custom group on video?

no,

**Comment by fakhrihawari** [comment]
updated

**Comment by fakhrihawari** [comment]
Updated on DEV and PROD

**Pull request merged**
